### ISSUE TITLE
Control panel Modem hangs on Ubuntu 24.04

### ISSUE THREAD

**Issue by quozl** [sugarlabs/sugar#1054]
Logs contain;

```
Traceback (most recent call last):
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 207, in get
    return self._data[country_code]
           ~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'xk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 459, in __select_option_cb
    self.show_section_view(option)
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 313, in show_section_view
    self._section_view = view_class(model,
                         ^^^^^^^^^^^^^^^^^
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/view.py", line 125, in __init__
    self.service_providers = self._model.ServiceProviders()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 275, in __init__
    self._db = ServiceProvidersParser()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 235, in __init__
    self._countries.sort(key=lambda x: names.get(x.attrib['code']))
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 235, in <lambda>
    self._countries.sort(key=lambda x: names.get(x.attrib['code']))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/sugar/extensions/cpsection/modemconfiguration/model.py", line 209, in get
    raise KeyError('Not found country name for code "%s"'
KeyError: 'Not found country name for code "xk"'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 374, in __cancel_clicked_cb
    self._section_view.undo()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'undo'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 383, in __accept_clicked_cb
    if self._section_view.needs_restart:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'needs_restart'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/jarabe/controlpanel/gui.py", line 383, in __accept_clicked_cb
    if self._section_view.needs_restart:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'needs_restart'

```

**Comment by vanshjohri09-collab** [comment]
@Dev10-sys Tested on Ubuntu.

The modem configuration still appears to crash in my setup.
Possibly I am not running the correct development build.

Could you clarify the recommended way to test this PR?

Happy to re-test once confirmed.

**Comment by Ravi-Poddar26** [comment]
Tested on Ubuntu 24.04 / Python 3.12:

KeyError: 'xk' is fixed locally using get() in CountryCodeParser.

Control Panel still crashes due to Gtk.VBox errors — GTK4 removed these widgets, so GTK3 code is incompatible.

Bulk replacements break Sugar; safe testing requires either a GTK3 environment (Ubuntu 22.04) or a full GTK4 port.

The country code fix works; UI crash is GTK-related.

**Comment by quozl** [comment]
GTK3 environment works fine in Ubuntu 24.04, 24.10, 25.04 and 25.10.  VBox was deprecated in GTK3.  Please put test reports relating to pull requests in the pull requests, and confine the issue to the problem at hand.

**Comment by Ravi-Poddar26** [comment]
Tested on Ubuntu 24.04 with Python 3.12 (GTK3). On the main branch, opening the Control Panel crashes in the modem configuration section with KeyError: 'xk', originating from CountryCodeParser during country sorting when an unknown country code is looked up.

I fetched and tested PR #1066 using git fetch origin pull/1066/head:pr-test and git checkout pr-test. The PR uses self._countries.sort(key=lambda x: names.get(x.attrib['code'])), where names is an instance of CountryCodeParser. Since CountryCodeParser.get() raises KeyError for unknown codes (as confirmed by existing tests), the crash with 'xk' still persists in my environment and the modem configuration section does not load successfully.

For verification, I modified the code locally to safely return a fallback value instead of raising KeyError for unknown country codes. After this change, the Control Panel loads correctly and the KeyError: 'xk' no longer appears. Based on this testing, PR #1066 does not fully resolve the issue in my environment, and handling unknown country codes safely inside CountryCodeParser.get() may prevent the crash.

proof :

<img width="809" height="243" alt="Image" src="https://github.com/user-attachments/assets/7a5e4f10-8bea-4539-868e-81c99e16d957" />
